export const APP_NAME = 'rtunes';
export const APP_TAGLINE = 'music';
export const TRACKING_ID = 'UA-87777712-1';
export const SC_CLIENT_ID = '51b1b4d87cf6def824d988d6ad3315ca';
export const IGNORE_AUTHORS = ['Mentioned_Videos', 'PlaylisterBot'];
export const DEFAULT_POST_TITLE = 'Untitled';
export const AUTHOR_URL = 'https://github.com/jake-g';
export const SOURCE_URL = 'https://github.com/jake-g/rtunes';
export const SEPARATOR = ' | ';
